import { createSlice } from "@reduxjs/toolkit";
import { RootState } from "../app/store";

export interface ConfigurationState {
    status: "idle" | "loading" | "succeeded" | "failed";
    appVersion: string;
    database: string;
    schema: string;
    connectionString: string;
}

const initialState: ConfigurationState = {
    status: "idle",
    appVersion: "",
    database: "",
    schema: "",
    connectionString: "",
};

export const counterSlice = createSlice({
    name: "counter",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {},
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
});

export const {} = counterSlice.actions;

export const selectConfiguration = (state: RootState): ConfigurationState => state.configuration;

export default counterSlice.reducer;
